### ISSUE TITLE
I can't launch heimdall-macos

### ISSUE THREAD

**Issue by Spoutnik97** [amo13/Heimdall#7]
I have the following error message : "Impossible d’ouvrir l’application « heimdall-frontend.app »." when i am trying to open the heidall-frontend.app file @amo13

**Comment by amo13** [comment]
Oh, I see.
Actually, I have not tested the frontend as I only need the binary for terminal.
I guess that the frontend does not work because it has not been maintained and updated for years.
Please use the binary for terminal instead.
